[theme]
base = "light"
primaryColor = "#DB3D42"
backgroundColor = "#F7F7F7"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#17181A"
font = "sans serif"

[server]
headless = true
maxUploadSize = 50

[browser]
gatherUsageStats = false
